name: Test Firebase Secret

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Firebase Service Account Secret
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            echo "FIREBASE_SERVICE_ACCOUNT is NOT set!"
            exit 1
          else
            echo "FIREBASE_SERVICE_ACCOUNT is set."
          fi